name: "fizzy"

services:
  rails:
    container_name: ${COMPOSE_PROJECT_NAME}-rails
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../../${COMPOSE_PROJECT_NAME}:/workspaces/${COMPOSE_PROJECT_NAME}:cached
    - ~/.config/gh:/home/dev/.config/gh:cached

    environment:
      GH_CONFIG_DIR: /home/dev/.config/gh

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
    - selenium

  selenium:
    container_name: ${COMPOSE_PROJECT_NAME}-selenium
    image: selenium/standalone-chromium
    restart: unless-stopped
