test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/files") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage", Rails.env, "files") %>

devminio:
  service: S3
  bucket: fizzy-dev-activestorage
  endpoint: "http://minio.localhost:39000"
  force_path_style: true
  request_checksum_calculation: when_required # default is when_supported with CRC64NVME checksum which FlashBlade doesn't support
  response_checksum_validation: when_required # default is when_supported with CRC64NVME checksum which FlashBlade doesn't support
  region: us-east-1 # default region required for signer
  access_key_id: minioadmin
  secret_access_key: minioadmin

cloudflare_production:
  service: S3
  endpoint: https://<%= ENV['CLOUDFLARE_ENDPOINT'] %>.eu.r2.cloudflarestorage.com
  access_key_id: <%= ENV["R2_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["R2_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV.fetch("R2_BUCKET", "lucianghinda") %>
  region: auto
  force_path_style: true
  request_checksum_calculation: when_required
  response_checksum_validation: when_required
